export const TOGGLE_FILTER = 'TOGGLE_FILTER'
export const UPDATE_VIN_CODES = 'UPDATE_VIN_CODES'
export const UPDATE_VIN_EVENTS = 'UPDATE_VIN_EVENTS'
export const UPDATE_VIN_COLORS = 'UPDATE_VIN_COLORS'
